### ISSUE TITLE
Impossible to create a new use case

### ISSUE THREAD

**Issue by ivanvaccarics** [ThingzDefense/IoT-Flock#1]
I'm trying to use your interesting tool to generate MQTT traffic but when i tried to create a new use case, the Qt creator return me the following error "Use case already exist". Moreover, the Qt creator seems to be not able to communicate with the database. Could you please help me? for me, your tool is very interesting and innovative. Thanks!

**Comment by gabbas4001** [comment]
Hi, 
   Please place the database file in the debug folder (also mentioned in installation steps).

Regards,
Ghazanfar Abbas

**Comment by ThingzDefense** [comment]
Hi,
  To avoid installation issues and easy to use, IoT Flock VM is shared on below link. 
  Downloading Link: https://mega.nz/file/RB5CBAoI#Q_q0tjXALIj3j2WCg8_lBT9HHSX0TF-juP_DJ1I4ADw
  Root Passwrod: iot123

  ******
  a. Desktop contains exe folder. 
  b. Code is also placed in tools folder ( you can open QT and it will appear to you)

Regards,
Syed Ghazanfar Abbas

**Comment by fatemehm** [comment]
@ThingzDefense 
Would you please do me a favor and share the VM link with me too? The link that you have shared above doesn't work. I have the same problem that @ivanv6 faced.

**Comment by paigejh** [comment]
@ThingzDefense May I also receive a link to the VM, please? I am encountering the same issue as well. 

Thank you in advance!

**Comment by paigejh** [comment]
For anyone looking for the VM file, here it is: https://drive.google.com/file/d/1oeCzEeTnFKFTO66GWe8M0ApzhY3iu5s-/view?usp=sharing

Kindly, 
Paige
