### ISSUE TITLE
Isue after build

### ISSUE THREAD

**Issue by davidsanchesgomez** [ThingzDefense/IoT-Flock#3]
Heloo, I`m planning on using your IoT Traffic generation to be able to execute mqtt and coap traffic for a project. 
When I was doing all the steps of the instalation guide I encounter a problem after building the program. When I run it and the window appears to enter a new UseCase, no matter what I put in the box name, it is telling me that the name already exists.

Also un General Messages in qt Creator i see this two lines, i don`t know if they are realated whit the error above:
-Project _ERROR: You need to set the ANDROID_NDK_ROOT environment variable to point to your Android NDK.
Could not read qmake configuration file /home/david/Qt/5.12.3/android_armv7/mkspecs/android-clang/qmake.conf.__

I hope you can help me to find the solutions
![imagen](https://user-images.githubusercontent.com/40458516/94995189-edf18e80-059c-11eb-95ac-9a335e868e0d.png)

David

**Comment by Ghitalazrek** [comment]
sotty i have the same prob what is the solution ?
