### ISSUE TITLE
Qt issue after build in VM 

### ISSUE THREAD

**Issue by Wajiullah** [ThingzDefense/IoT-Flock#6]
Hey. I installed IoT_Flock_VM and after installing VM when I run the IoTFlock-GUI or IoTFlock-Console project the following message appears 
![Capture](https://user-images.githubusercontent.com/67365694/111599417-0cb5ab80-87f2-11eb-82e5-74c73c9930d8.PNG)

01:50:51: Starting /home/iot/main/tools/IoT-Flock-master/build-IoTFlock-Desktop_Qt_5_12_3_GCC_64bit-Debug/IoTFlock-GUI ...
QFSFileEngine::open: No file name specified

**Comment by DilwarS** [comment]
I am also facing the same issue.
